// Curated company boards for public ATS feeds. Slugs are best-effort; a
// company whose board 404s is logged and skipped by the fetcher.
export interface AtsCompany {
  name: string;
  slug: string;
}

export const GREENHOUSE_COMPANIES: AtsCompany[] = [
  { name: "Remote", slug: "remote" },
  { name: "Samsara", slug: "samsara" },
  { name: "Fingerprint", slug: "fingerprint" },
  { name: "Media.Monks", slug: "mediamonks" },
  { name: "Affirm", slug: "affirm" },
  { name: "DoorDash", slug: "doordash" },
  { name: "Betterment", slug: "betterment" },
  { name: "MLB", slug: "mlb" },
  { name: "LinkedIn", slug: "linkedin" },
  { name: "NBA", slug: "nba" },
  { name: "Stripe", slug: "stripe" },
  { name: "Coinbase", slug: "coinbase" },
  { name: "Twilio", slug: "twilio" },
  { name: "GitHub", slug: "github" },
  { name: "Zapier", slug: "zapier" },
  { name: "Customer.io", slug: "customerio" },
  { name: "Axios", slug: "axios" },
  { name: "Circle", slug: "circle" },
  { name: "Podia", slug: "podia" },
  { name: "Harvest", slug: "harvest" },
  { name: "G2i", slug: "g2i" },
  { name: "Yoko Co", slug: "yokoco" },
  { name: "Nathan James", slug: "nathanjames" },
  { name: "Filestage", slug: "filestage" },
  { name: "Knack", slug: "knack" },
  { name: "Float", slug: "float" },
  { name: "Animalz", slug: "animalz" },
  { name: "Kinsta", slug: "kinsta" },
  { name: "Uscreen", slug: "uscreen" },
  { name: "MailerLite", slug: "mailerlite" },
  { name: "Sticker Mule", slug: "stickermule" },
  { name: "DataStax", slug: "datastax" },
  { name: "XM", slug: "xm" },
  { name: "Help Scout", slug: "helpscout" },
  { name: "Doximity", slug: "doximity" },
  { name: "Oddball", slug: "oddball" },
  { name: "Fleetio", slug: "fleetio" },
  { name: "AgencyAnalytics", slug: "agencyanalytics" },
  { name: "Paymentology", slug: "paymentology" },
  { name: "Lemon.io", slug: "lemonio" },
  { name: "Automattic", slug: "automattic" },
  { name: "Modern Tribe", slug: "moderntribe" },
  { name: "Shogun", slug: "shogun" },
  { name: "X-Team", slug: "xteam" },
  { name: "TestGorilla", slug: "testgorilla" },
  { name: "Proxify", slug: "proxify" },
  { name: "ReCharge Payments", slug: "rechargepayments" },
  { name: "Close", slug: "close" },
  { name: "OnTheGoSystems", slug: "onthegosystems" },
  { name: "Toggl", slug: "toggl" },
  { name: "Aha!", slug: "aha" },
  { name: "TaxJar", slug: "taxjar" },
  { name: "Hotjar", slug: "hotjar" },
  { name: "Toptal", slug: "toptal" },
  { name: "Contra", slug: "contra" },
  { name: "Lumenalta", slug: "lumenalta" },
  { name: "Mercy Corps", slug: "mercycorps" },
  { name: "Save the Children", slug: "savethechildren" },
  { name: "International Rescue Committee", slug: "internationalrescuecommittee" },
  { name: "CARE", slug: "care" },
  { name: "PATH", slug: "path" },
  { name: "FHI 360", slug: "fhi360" },
  { name: "Chemonics", slug: "chemonics" },
  { name: "DAI", slug: "dai" },
  { name: "RTI International", slug: "rtiinternational" },
  { name: "Clinton Health Access Initiative", slug: "clintonhealthaccessinitiative" },
  { name: "World Resources Institute", slug: "worldresourcesinstitute" },
  { name: "Abt Global", slug: "abtglobal" },
  { name: "TechnoServe", slug: "technoserve" },
  { name: "Winrock International", slug: "winrockinternational" },
  { name: "Pact", slug: "pact" },
  { name: "Plan International", slug: "planinternational" },
  { name: "Oxfam America", slug: "oxfamamerica" },
  { name: "World Vision", slug: "worldvision" },
  { name: "Catholic Relief Services", slug: "catholicreliefservices" },
];

export const LEVER_COMPANIES: AtsCompany[] = [
  { name: "Shopify", slug: "shopify" },
  { name: "Klarna", slug: "klarna" },
  { name: "Palantir", slug: "palantir" },
  { name: "Rackspace", slug: "rackspace" },
  { name: "Techstars", slug: "techstars" },
  { name: "Xero", slug: "xero" },
  { name: "Getty Images", slug: "gettyimages" },
  { name: "1Password", slug: "1password" },
  { name: "Netflix", slug: "netflix" },
  { name: "Spotify", slug: "spotify" },
  { name: "Yelp", slug: "yelp" },
  { name: "Lyft", slug: "lyft" },
  { name: "Pinterest", slug: "pinterest" },
  { name: "Coursera", slug: "coursera" },
  { name: "Eventbrite", slug: "eventbrite" },
  { name: "Zendesk", slug: "zendesk" },
  { name: "Box", slug: "box" },
  { name: "Atlassian", slug: "atlassian" },
  { name: "Miro", slug: "miro" },
  { name: "Figma", slug: "figma" },
  { name: "Notion", slug: "notion" },
  { name: "Linear", slug: "linear" },
  { name: "Vercel", slug: "vercel" },
  { name: "Supabase", slug: "supabase" },
  { name: "Railway", slug: "railway" },
  { name: "Fly.io", slug: "flyio" },
  { name: "Render", slug: "render" },
  { name: "Netlify", slug: "netlify" },
  { name: "Clerk", slug: "clerk" },
  { name: "Auth0", slug: "auth0" },
  { name: "Okta", slug: "okta" },
  { name: "Authzed", slug: "authzed" },
  { name: "Descope", slug: "descope" },
  { name: "Stytch", slug: "stytch" },
  { name: "Kinde", slug: "kinde" },
  { name: "PropelAuth", slug: "propelauth" },
  { name: "WorkOS", slug: "workos" },
  { name: "Merge", slug: "merge" },
  { name: "Finch", slug: "finch" },
  { name: "Rutter", slug: "rutter" },
  { name: "Terra", slug: "terra" },
  { name: "Vital", slug: "vital" },
  { name: "Human API", slug: "humanapi" },
  { name: "Healthie", slug: "healthie" },
  { name: "Welkin Health", slug: "welkinhealth" },
  { name: "Canvas Medical", slug: "canvasmedical" },
  { name: "Elation Health", slug: "elationhealth" },
  { name: "Hint Health", slug: "hinthealth" },
  { name: "Spruce Health", slug: "sprucehealth" },
  { name: "Ro", slug: "ro" },
  { name: "HealthJoy", slug: "healthjoy" },
  { name: "Amino", slug: "amino" },
  { name: "Castlight Health", slug: "castlighthealth" },
  { name: "Accolade", slug: "accolade" },
  { name: "Quantum Health", slug: "quantumhealth" },
  { name: "Virgin Pulse", slug: "virginpulse" },
  { name: "Limeade", slug: "limeade" },
  { name: "Sharecare", slug: "sharecare" },
  { name: "Welltok", slug: "welltok" },
  { name: "LSA Global", slug: "lsaglobal" },
  { name: "RainFocus", slug: "rainfocus" },
  { name: "Included Health", slug: "includedhealth" },
  { name: "Five Star Solutions", slug: "fivestarsolutions" },
  { name: "Huckleberry Labs", slug: "huckleberrylabs" },
  { name: "Welo Global", slug: "weloglobal" },
  { name: "The Athletic", slug: "theathletic" },
  { name: "10up", slug: "10up" },
  { name: "15Five", slug: "15five" },
  { name: "7pace", slug: "7pace" },
  { name: "8fit", slug: "8fit" },
  { name: "Ableton", slug: "ableton" },
  { name: "Abstract", slug: "abstract" },
  { name: "Academic Partnerships", slug: "academicpartnerships" },
  { name: "Accion", slug: "accion" },
];

export const ASHBY_COMPANIES: AtsCompany[] = [
  { name: "Deel", slug: "deel" },
  { name: "Vanta", slug: "vanta" },
  { name: "Ramp", slug: "ramp" },
  { name: "Brex", slug: "brex" },
  { name: "Mercury", slug: "mercury" },
  { name: "Rippling", slug: "rippling" },
  { name: "Gusto", slug: "gusto" },
  { name: "Lattice", slug: "lattice" },
  { name: "Retool", slug: "retool" },
  { name: "Checkr", slug: "checkr" },
  { name: "Persona", slug: "persona" },
  { name: "Plaid", slug: "plaid" },
  { name: "Colonist", slug: "colonist" },
  { name: "Runway", slug: "runway" },
  { name: "Etched", slug: "etched" },
  { name: "Synthetic", slug: "synthetic" },
  { name: "Tailor", slug: "tailor" },
  { name: "Sparrow", slug: "sparrow" },
  { name: "Ashby", slug: "ashby" },
  { name: "Sourcegraph", slug: "sourcegraph" },
  { name: "Grafana Labs", slug: "grafanalabs" },
  { name: "GitLab", slug: "gitlab" },
  { name: "Snyk", slug: "snyk" },
  { name: "Wiz", slug: "wiz" },
  { name: "Lacework", slug: "lacework" },
  { name: "Orca Security", slug: "orcasecurity" },
  { name: "Sysdig", slug: "sysdig" },
  { name: "Aqua Security", slug: "aquasecurity" },
  { name: "HashiCorp", slug: "hashicorp" },
  { name: "Confluent", slug: "confluent" },
  { name: "Snowflake", slug: "snowflake" },
  { name: "Databricks", slug: "databricks" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "Elastic", slug: "elastic" },
  { name: "Neo4j", slug: "neo4j" },
  { name: "Redis", slug: "redis" },
  { name: "Cockroach Labs", slug: "cockroachlabs" },
  { name: "PlanetScale", slug: "planetscale" },
  { name: "Neon", slug: "neon" },
  { name: "Upstash", slug: "upstash" },
  { name: "Momento", slug: "momento" },
  { name: "Xata", slug: "xata" },
  { name: "Turso", slug: "turso" },
  { name: "Convex", slug: "convex" },
  { name: "Inngest", slug: "inngest" },
  { name: "Trigger.dev", slug: "triggerdev" },
  { name: "Temporal", slug: "temporal" },
  { name: "Cadence", slug: "cadence" },
  { name: "Airbyte", slug: "airbyte" },
  { name: "Fivetran", slug: "fivetran" },
  { name: "Meltano", slug: "meltano" },
  { name: "Estuary", slug: "estuary" },
  { name: "Decodable", slug: "decodable" },
  { name: "Meroxa", slug: "meroxa" },
  { name: "Materialize", slug: "materialize" },
  { name: "Rockset", slug: "rockset" },
  { name: "ClickHouse", slug: "clickhouse" },
  { name: "StarTree", slug: "startree" },
  { name: "Imply", slug: "imply" },
  { name: "ScyllaDB", slug: "scylladb" },
  { name: "Yugabyte", slug: "yugabyte" },
  { name: "PingCAP", slug: "pingcap" },
  { name: "SingleStore", slug: "singlestore" },
  { name: "MariaDB", slug: "mariadb" },
  { name: "Percona", slug: "percona" },
  { name: "Aiven", slug: "aiven" },
  { name: "Instaclustr", slug: "instaclustr" },
  { name: "Timescale", slug: "timescale" },
  { name: "QuestDB", slug: "questdb" },
  { name: "InfluxData", slug: "influxdata" },
  { name: "VictoriaMetrics", slug: "victoriametrics" },
  { name: "MotherDuck", slug: "motherduck" },
  { name: "DuckDB Labs", slug: "duckdblabs" },
  { name: "Starburst", slug: "starburst" },
  { name: "Dremio", slug: "dremio" },
];

export const BREEZY_COMPANIES: AtsCompany[] = [
  { name: "Remote Year", slug: "remote-year" },
  { name: "Vetsez", slug: "vetsez" },
  { name: "Float Health", slug: "float-health" },
  { name: "Altitude Roofing", slug: "altitude-roofing" },
  { name: "Mind Computing", slug: "mind-computing" },
  { name: "Keylime", slug: "keylime" },
  { name: "Leafr", slug: "leafr" },
  { name: "Zippee", slug: "zippee" },
  { name: "GreedyGame", slug: "greedygame" },
  { name: "Geeta Group", slug: "geeta-group" },
  { name: "Booster Box", slug: "booster-box" },
  { name: "Docebo", slug: "docebo" },
  { name: "Dodge Data and Analytics", slug: "dodge-data-and-analytics" },
  { name: "Tally", slug: "tally" },
  { name: "Portable", slug: "portable" },
  { name: "Thinkific", slug: "thinkific" },
  { name: "Brevo", slug: "brevo" },
  { name: "Sinch", slug: "sinch" },
  { name: "Vonage", slug: "vonage" },
  { name: "MessageBird", slug: "messagebird" },
  { name: "Plivo", slug: "plivo" },
  { name: "Telnyx", slug: "telnyx" },
  { name: "Bandwidth", slug: "bandwidth" },
  { name: "RingCentral", slug: "ringcentral" },
  { name: "8x8", slug: "8x8" },
  { name: "Dialpad", slug: "dialpad" },
  { name: "Talkdesk", slug: "talkdesk" },
  { name: "Five9", slug: "five9" },
  { name: "Genesys", slug: "genesys" },
  { name: "Nice InContact", slug: "nice-incontact" },
  { name: "Aircall", slug: "aircall" },
  { name: "CloudTalk", slug: "cloudtalk" },
  { name: "JustCall", slug: "justcall" },
  { name: "Krisp", slug: "krisp" },
  { name: "Otter.ai", slug: "otter-ai" },
  { name: "Descript", slug: "descript" },
  { name: "Riverside.fm", slug: "riverside-fm" },
  { name: "SquadCast", slug: "squadcast" },
  { name: "Zencastr", slug: "zencastr" },
  { name: "RedCircle", slug: "redcircle" },
  { name: "Simplecast", slug: "simplecast" },
  { name: "Transistor.fm", slug: "transistor-fm" },
  { name: "Captivate.fm", slug: "captivate-fm" },
  { name: "Buzzsprout", slug: "buzzsprout" },
  { name: "Libsyn", slug: "libsyn" },
  { name: "Blubrry", slug: "blubrry" },
  { name: "Podbean", slug: "podbean" },
  { name: "Spreaker", slug: "spreaker" },
  { name: "Audioboom", slug: "audioboom" },
  { name: "Omny Studio", slug: "omny-studio" },
  { name: "Megaphone", slug: "megaphone" },
  { name: "Triton Digital", slug: "triton-digital" },
  { name: "AdsWizz", slug: "adswizz" },
  { name: "Targetspot", slug: "targetspot" },
  { name: "DAX", slug: "dax" },
  { name: "Acast", slug: "acast" },
  { name: "Sounder.fm", slug: "sounder-fm" },
  { name: "Veritonic", slug: "veritonic" },
  { name: "Podsights", slug: "podsights" },
  { name: "Chartable", slug: "chartable" },
  { name: "Magellan AI", slug: "magellan-ai" },
  { name: "Podchaser", slug: "podchaser" },
  { name: "Listen Notes", slug: "listen-notes" },
  { name: "Podscribe", slug: "podscribe" },
  { name: "Backtracks", slug: "backtracks" },
  { name: "CoHost", slug: "cohost" },
  { name: "Quill", slug: "quill" },
  { name: "Pacific Content", slug: "pacific-content" },
  { name: "Pineapple Street", slug: "pineapple-street" },
  { name: "Gimlet", slug: "gimlet" },
  { name: "Parcast", slug: "parcast" },
  { name: "Wondery", slug: "wondery" },
  { name: "Luminary", slug: "luminary" },
  { name: "Pushkin Industries", slug: "pushkin-industries" },
  { name: "Slate", slug: "slate" },
];
