// Curated company boards for public ATS feeds. Slugs are best-effort; a
// company whose board 404s is logged and skipped by the fetcher.
export interface AtsCompany {
  name: string;
  slug: string;
}

export const GREENHOUSE_COMPANIES: AtsCompany[] = [
  { name: "Remote", slug: "remote" },
  { name: "Samsara", slug: "samsara" },
  { name: "Fingerprint", slug: "fingerprint" },
  { name: "Media.Monks", slug: "mediamonks" },
  { name: "Affirm", slug: "affirm" },
  { name: "DoorDash", slug: "doordash" },
  { name: "Betterment", slug: "betterment" },
  { name: "MLB", slug: "mlb" },
  { name: "LinkedIn", slug: "linkedin" },
  { name: "NBA", slug: "nba" },
  { name: "Stripe", slug: "stripe" },
  { name: "Coinbase", slug: "coinbase" },
  { name: "Twilio", slug: "twilio" },
  { name: "GitHub", slug: "github" },
  { name: "Zapier", slug: "zapier" },
  { name: "Customer.io", slug: "customerio" },
  { name: "Axios", slug: "axios" },
  { name: "Circle", slug: "circle" },
  { name: "Podia", slug: "podia" },
  { name: "Harvest", slug: "harvest" },
  { name: "G2i", slug: "g2i" },
  { name: "Yoko Co", slug: "yokoco" },
  { name: "Nathan James", slug: "nathanjames" },
  { name: "Filestage", slug: "filestage" },
  { name: "Knack", slug: "knack" },
  { name: "Float", slug: "float" },
  { name: "Animalz", slug: "animalz" },
  { name: "Kinsta", slug: "kinsta" },
  { name: "Uscreen", slug: "uscreen" },
  { name: "MailerLite", slug: "mailerlite" },
  { name: "Sticker Mule", slug: "stickermule" },
  { name: "DataStax", slug: "datastax" },
  { name: "XM", slug: "xm" },
  { name: "Help Scout", slug: "helpscout" },
  { name: "Doximity", slug: "doximity" },
  { name: "Oddball", slug: "oddball" },
  { name: "Fleetio", slug: "fleetio" },
  { name: "AgencyAnalytics", slug: "agencyanalytics" },
  { name: "Paymentology", slug: "paymentology" },
  { name: "Lemon.io", slug: "lemonio" },
  { name: "Automattic", slug: "automattic" },
  { name: "Modern Tribe", slug: "moderntribe" },
  { name: "Shogun", slug: "shogun" },
  { name: "X-Team", slug: "xteam" },
  { name: "TestGorilla", slug: "testgorilla" },
  { name: "Proxify", slug: "proxify" },
  { name: "ReCharge Payments", slug: "rechargepayments" },
  { name: "Close", slug: "close" },
  { name: "OnTheGoSystems", slug: "onthegosystems" },
  { name: "Toggl", slug: "toggl" },
  { name: "Aha!", slug: "aha" },
  { name: "TaxJar", slug: "taxjar" },
  { name: "Hotjar", slug: "hotjar" },
  { name: "Toptal", slug: "toptal" },
  { name: "Contra", slug: "contra" },
  { name: "Lumenalta", slug: "lumenalta" },
  { name: "Mercy Corps", slug: "mercycorps" },
  { name: "Save the Children", slug: "savethechildren" },
  { name: "International Rescue Committee", slug: "internationalrescuecommittee" },
  { name: "CARE", slug: "care" },
  { name: "PATH", slug: "path" },
  { name: "FHI 360", slug: "fhi360" },
  { name: "Chemonics", slug: "chemonics" },
  { name: "DAI", slug: "dai" },
  { name: "RTI International", slug: "rtiinternational" },
  { name: "Clinton Health Access Initiative", slug: "clintonhealthaccessinitiative" },
  { name: "World Resources Institute", slug: "worldresourcesinstitute" },
  { name: "Abt Global", slug: "abtglobal" },
  { name: "TechnoServe", slug: "technoserve" },
  { name: "Winrock International", slug: "winrockinternational" },
  { name: "Pact", slug: "pact" },
  { name: "Plan International", slug: "planinternational" },
  { name: "Oxfam America", slug: "oxfamamerica" },
  { name: "World Vision", slug: "worldvision" },
  { name: "Catholic Relief Services", slug: "catholicreliefservices" },
  // Added Aug 2026 batch — 75 more Greenhouse companies
  { name: "HubSpot", slug: "hubspot" },
  { name: "Duolingo", slug: "duolingo" },
  { name: "Lucid Motors", slug: "lucidmotors" },
  { name: "Gong", slug: "gong" },
  { name: "J.D. Power", slug: "jdpower" },
  { name: "Scout24", slug: "scout24" },
  { name: "Hopin", slug: "hopin" },
  { name: "Articulate", slug: "articulate" },
  { name: "Buffer", slug: "buffer" },
  { name: "Doist", slug: "doist" },
  { name: "DuckDuckGo", slug: "duckduckgo" },
  { name: "InVision", slug: "invision" },
  { name: "Kraken", slug: "kraken" },
  { name: "LottieFiles", slug: "lottiefiles" },
  { name: "Mozilla", slug: "mozilla" },
  { name: "Netdata", slug: "netdata" },
  { name: "OpenProject", slug: "openproject" },
  { name: "Postman", slug: "postman" },
  { name: "Prezly", slug: "prezly" },
  { name: "Skillshare", slug: "skillshare" },
  { name: "Stack Overflow", slug: "stackoverflow" },
  { name: "Status.im", slug: "statusim" },
  { name: "Swissborg", slug: "swissborg" },
  { name: "Upwork", slug: "upwork" },
  { name: "Webflow", slug: "webflow" },
  { name: "Wikimedia Foundation", slug: "wikimediafoundation" },
  { name: "Appwrite", slug: "appwrite" },
  { name: "Arkose Labs", slug: "arkoselabs" },
  { name: "Astronomer", slug: "astronomer" },
  { name: "Balsamiq", slug: "balsamiq" },
  { name: "Bitpanda", slug: "bitpanda" },
  { name: "Blockchain.com", slug: "blockchaincom" },
  { name: "Bolt", slug: "bolt" },
  { name: "Branch", slug: "branch" },
  { name: "Brave", slug: "brave" },
  { name: "BrowserStack", slug: "browserstack" },
  { name: "Canva", slug: "canva" },
  { name: "ClickUp", slug: "clickup" },
  { name: "Datadog", slug: "datadog" },
  { name: "Datarobot", slug: "datarobot" },
  { name: "DeepL", slug: "deepl" },
  { name: "DigitalOcean", slug: "digitalocean" },
  { name: "Discord", slug: "discord" },
  { name: "Docker", slug: "docker" },
  { name: "Docusign", slug: "docusign" },
  { name: "Dribbble", slug: "dribbble" },
  { name: "Dropbox", slug: "dropbox" },
  { name: "Dynatrace", slug: "dynatrace" },
  { name: "Envato", slug: "envato" },
  { name: "Expensify", slug: "expensify" },
  { name: "Fastly", slug: "fastly" },
  { name: "Fireblocks", slug: "fireblocks" },
  { name: "Freshworks", slug: "freshworks" },
  { name: "Front", slug: "front" },
  { name: "FullStory", slug: "fullstory" },
  { name: "Ghost", slug: "ghost" },
  { name: "Giphy", slug: "giphy" },
  { name: "Gitpod", slug: "gitpod" },
  { name: "Glassdoor", slug: "glassdoor" },
  { name: "Glean", slug: "glean" },
  { name: "Sendbird", slug: "sendbird" },
  { name: "Grammarly", slug: "grammarly" },
  { name: "Gumroad", slug: "gumroad" },
  { name: "HackerRank", slug: "hackerrank" },
  { name: "Headspace", slug: "headspace" },
  { name: "HelloSign", slug: "hellosign" },
  { name: "Heroku", slug: "heroku" },
  { name: "Hugging Face", slug: "huggingface" },
  { name: "Intercom", slug: "intercom" },
  { name: "InVideo", slug: "invideo" },
  { name: "Itch.io", slug: "itchio" },
  { name: "Jamf", slug: "jamf" },
  { name: "Jellyfish", slug: "jellyfish" },
  { name: "JetBrains", slug: "jetbrains" },
  { name: "Klaviyo", slug: "klaviyo" },
];

export const LEVER_COMPANIES: AtsCompany[] = [
  { name: "Shopify", slug: "shopify" },
  { name: "Klarna", slug: "klarna" },
  { name: "Palantir", slug: "palantir" },
  { name: "Rackspace", slug: "rackspace" },
  { name: "Techstars", slug: "techstars" },
  { name: "Xero", slug: "xero" },
  { name: "Getty Images", slug: "gettyimages" },
  { name: "1Password", slug: "1password" },
  { name: "Netflix", slug: "netflix" },
  { name: "Spotify", slug: "spotify" },
  { name: "Yelp", slug: "yelp" },
  { name: "Lyft", slug: "lyft" },
  { name: "Pinterest", slug: "pinterest" },
  { name: "Coursera", slug: "coursera" },
  { name: "Eventbrite", slug: "eventbrite" },
  { name: "Zendesk", slug: "zendesk" },
  { name: "Box", slug: "box" },
  { name: "Atlassian", slug: "atlassian" },
  { name: "Miro", slug: "miro" },
  { name: "Figma", slug: "figma" },
  { name: "Notion", slug: "notion" },
  { name: "Linear", slug: "linear" },
  { name: "Vercel", slug: "vercel" },
  { name: "Supabase", slug: "supabase" },
  { name: "Railway", slug: "railway" },
  { name: "Fly.io", slug: "flyio" },
  { name: "Render", slug: "render" },
  { name: "Netlify", slug: "netlify" },
  { name: "Clerk", slug: "clerk" },
  { name: "Auth0", slug: "auth0" },
  { name: "Okta", slug: "okta" },
  { name: "Authzed", slug: "authzed" },
  { name: "Descope", slug: "descope" },
  { name: "Stytch", slug: "stytch" },
  { name: "Kinde", slug: "kinde" },
  { name: "PropelAuth", slug: "propelauth" },
  { name: "WorkOS", slug: "workos" },
  { name: "Merge", slug: "merge" },
  { name: "Finch", slug: "finch" },
  { name: "Rutter", slug: "rutter" },
  { name: "Terra", slug: "terra" },
  { name: "Vital", slug: "vital" },
  { name: "Human API", slug: "humanapi" },
  { name: "Healthie", slug: "healthie" },
  { name: "Welkin Health", slug: "welkinhealth" },
  { name: "Canvas Medical", slug: "canvasmedical" },
  { name: "Elation Health", slug: "elationhealth" },
  { name: "Hint Health", slug: "hinthealth" },
  { name: "Spruce Health", slug: "sprucehealth" },
  { name: "Ro", slug: "ro" },
  { name: "HealthJoy", slug: "healthjoy" },
  { name: "Amino", slug: "amino" },
  { name: "Castlight Health", slug: "castlighthealth" },
  { name: "Accolade", slug: "accolade" },
  { name: "Quantum Health", slug: "quantumhealth" },
  { name: "Virgin Pulse", slug: "virginpulse" },
  { name: "Limeade", slug: "limeade" },
  { name: "Sharecare", slug: "sharecare" },
  { name: "Welltok", slug: "welltok" },
  { name: "LSA Global", slug: "lsaglobal" },
  { name: "RainFocus", slug: "rainfocus" },
  { name: "Included Health", slug: "includedhealth" },
  { name: "Five Star Solutions", slug: "fivestarsolutions" },
  { name: "Huckleberry Labs", slug: "huckleberrylabs" },
  { name: "Welo Global", slug: "weloglobal" },
  { name: "The Athletic", slug: "theathletic" },
  { name: "10up", slug: "10up" },
  { name: "15Five", slug: "15five" },
  { name: "7pace", slug: "7pace" },
  { name: "8fit", slug: "8fit" },
  { name: "Ableton", slug: "ableton" },
  { name: "Abstract", slug: "abstract" },
  { name: "Academic Partnerships", slug: "academicpartnerships" },
  { name: "Accion", slug: "accion" },
  // Added Aug 2026 batch — 75 more Lever companies
  { name: "Airtable", slug: "airtable" },
  { name: "Algolia", slug: "algolia" },
  { name: "Amplitude", slug: "amplitude" },
  { name: "Benchling", slug: "benchling" },
  { name: "Bitly", slug: "bitly" },
  { name: "Braze", slug: "braze" },
  { name: "Carta", slug: "carta" },
  { name: "Chorus.ai", slug: "chorusai" },
  { name: "Clever", slug: "clever" },
  { name: "Cloudinary", slug: "cloudinary" },
  { name: "Dataiku", slug: "dataiku" },
  { name: "Datto", slug: "datto" },
  { name: "Divvy", slug: "divvy" },
  { name: "Drift", slug: "drift" },
  { name: "Envoy", slug: "envoy" },
  { name: "Etsy", slug: "etsy" },
  { name: "Evernote", slug: "evernote" },
  { name: "Faire", slug: "faire" },
  { name: "Fast", slug: "fast" },
  { name: "Flexport", slug: "flexport" },
  { name: "Flywire", slug: "flywire" },
  { name: "Forge", slug: "forge" },
  { name: "Forter", slug: "forter" },
  { name: "Frame.io", slug: "frameio" },
  { name: "G2", slug: "g2" },
  { name: "Geckoboard", slug: "geckoboard" },
  { name: "Getir", slug: "getir" },
  { name: "GoCardless", slug: "gocardless" },
  { name: "GoPuff", slug: "gopuff" },
  { name: "Gremlin", slug: "gremlin" },
  { name: "Grubhub", slug: "grubhub" },
  { name: "Guideline", slug: "guideline" },
  { name: "Guild Education", slug: "guildeducation" },
  { name: "HackerOne", slug: "hackerone" },
  { name: "Hinge", slug: "hinge" },
  { name: "HomeAdvisor", slug: "homeadvisor" },
  { name: "Honey", slug: "honey" },
  { name: "Hootsuite", slug: "hootsuite" },
  { name: "Hypercontext", slug: "hypercontext" },
  { name: "Impossible Foods", slug: "impossiblefoods" },
  { name: "Instacart", slug: "instacart" },
  { name: "Instapage", slug: "instapage" },
  { name: "iRobot", slug: "irobot" },
  { name: "Iterable", slug: "iterable" },
  { name: "Karat", slug: "karat" },
  { name: "Motive", slug: "motive" },
  { name: "Kong", slug: "kong" },
  { name: "Kustomer", slug: "kustomer" },
  { name: "Leadfeeder", slug: "leadfeeder" },
  { name: "Legacy", slug: "legacy" },
  { name: "LendingHome", slug: "lendinghome" },
  { name: "LendingTree", slug: "lendingtree" },
  { name: "GoTo", slug: "goto" },
  { name: "Lucidchart", slug: "lucidchart" },
  { name: "ManoMano", slug: "manomano" },
  { name: "Mixpanel", slug: "mixpanel" },
  { name: "Monday.com", slug: "mondaycom" },
  { name: "Mux", slug: "mux" },
  { name: "Namely", slug: "namely" },
  { name: "Navan", slug: "navan" },
  { name: "Nearpod", slug: "nearpod" },
  { name: "Newsela", slug: "newsela" },
  { name: "Nexthink", slug: "nexthink" },
  { name: "Noom", slug: "noom" },
  { name: "Noyo", slug: "noyo" },
  { name: "Outreach", slug: "outreach" },
  { name: "Pendo", slug: "pendo" },
  { name: "Postmates", slug: "postmates" },
  { name: "Qualtrics", slug: "qualtrics" },
  { name: "Quizlet", slug: "quizlet" },
  { name: "Recurly", slug: "recurly" },
  { name: "Reforge", slug: "reforge" },
  { name: "Robinhood", slug: "robinhood" },
  { name: "Rocket Lawyer", slug: "rocketlawyer" },
  { name: "Root Insurance", slug: "rootinsurance" },
];

export const ASHBY_COMPANIES: AtsCompany[] = [
  { name: "Deel", slug: "deel" },
  { name: "Vanta", slug: "vanta" },
  { name: "Ramp", slug: "ramp" },
  { name: "Brex", slug: "brex" },
  { name: "Mercury", slug: "mercury" },
  { name: "Rippling", slug: "rippling" },
  { name: "Gusto", slug: "gusto" },
  { name: "Lattice", slug: "lattice" },
  { name: "Retool", slug: "retool" },
  { name: "Checkr", slug: "checkr" },
  { name: "Persona", slug: "persona" },
  { name: "Plaid", slug: "plaid" },
  { name: "Colonist", slug: "colonist" },
  { name: "Runway", slug: "runway" },
  { name: "Etched", slug: "etched" },
  { name: "Synthetic", slug: "synthetic" },
  { name: "Tailor", slug: "tailor" },
  { name: "Sparrow", slug: "sparrow" },
  { name: "Ashby", slug: "ashby" },
  { name: "Sourcegraph", slug: "sourcegraph" },
  { name: "Grafana Labs", slug: "grafanalabs" },
  { name: "GitLab", slug: "gitlab" },
  { name: "Snyk", slug: "snyk" },
  { name: "Wiz", slug: "wiz" },
  { name: "Lacework", slug: "lacework" },
  { name: "Orca Security", slug: "orcasecurity" },
  { name: "Sysdig", slug: "sysdig" },
  { name: "Aqua Security", slug: "aquasecurity" },
  { name: "HashiCorp", slug: "hashicorp" },
  { name: "Confluent", slug: "confluent" },
  { name: "Snowflake", slug: "snowflake" },
  { name: "Databricks", slug: "databricks" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "Elastic", slug: "elastic" },
  { name: "Neo4j", slug: "neo4j" },
  { name: "Redis", slug: "redis" },
  { name: "Cockroach Labs", slug: "cockroachlabs" },
  { name: "PlanetScale", slug: "planetscale" },
  { name: "Neon", slug: "neon" },
  { name: "Upstash", slug: "upstash" },
  { name: "Momento", slug: "momento" },
  { name: "Xata", slug: "xata" },
  { name: "Turso", slug: "turso" },
  { name: "Convex", slug: "convex" },
  { name: "Inngest", slug: "inngest" },
  { name: "Trigger.dev", slug: "triggerdev" },
  { name: "Temporal", slug: "temporal" },
  { name: "Cadence", slug: "cadence" },
  { name: "Airbyte", slug: "airbyte" },
  { name: "Fivetran", slug: "fivetran" },
  { name: "Meltano", slug: "meltano" },
  { name: "Estuary", slug: "estuary" },
  { name: "Decodable", slug: "decodable" },
  { name: "Meroxa", slug: "meroxa" },
  { name: "Materialize", slug: "materialize" },
  { name: "Rockset", slug: "rockset" },
  { name: "ClickHouse", slug: "clickhouse" },
  { name: "StarTree", slug: "startree" },
  { name: "Imply", slug: "imply" },
  { name: "ScyllaDB", slug: "scylladb" },
  { name: "Yugabyte", slug: "yugabyte" },
  { name: "PingCAP", slug: "pingcap" },
  { name: "SingleStore", slug: "singlestore" },
  { name: "MariaDB", slug: "mariadb" },
  { name: "Percona", slug: "percona" },
  { name: "Aiven", slug: "aiven" },
  { name: "Instaclustr", slug: "instaclustr" },
  { name: "Timescale", slug: "timescale" },
  { name: "QuestDB", slug: "questdb" },
  { name: "InfluxData", slug: "influxdata" },
  { name: "VictoriaMetrics", slug: "victoriametrics" },
  { name: "MotherDuck", slug: "motherduck" },
  { name: "DuckDB Labs", slug: "duckdblabs" },
  { name: "Starburst", slug: "starburst" },
  { name: "Dremio", slug: "dremio" },
  // Added Aug 2026 batch — 74 more Ashby companies (1 dupe skipped: Confluent already listed)
  { name: "Quora", slug: "quora" },
  { name: "Arintra", slug: "arintra" },
  { name: "Rillet", slug: "rillet" },
  { name: "Protégé", slug: "protg" },
  { name: "A Place for Mom", slug: "aplaceformom" },
  { name: "Cursor", slug: "cursor" },
  { name: "Sierra", slug: "sierra" },
  { name: "UiPath", slug: "uipath" },
  { name: "Clay", slug: "clay" },
  { name: "Harvey", slug: "harvey" },
  { name: "Deliveroo", slug: "deliveroo" },
  { name: "Reddit", slug: "reddit" },
  { name: "Hiya", slug: "hiya" },
  { name: "Sentient Labs", slug: "sentientlabs" },
  { name: "Lottie", slug: "lottie" },
  { name: "Semperis", slug: "semperis" },
  { name: "Harmonic Security", slug: "harmonicsecurity" },
  { name: "Juniper Square", slug: "junipersquare" },
  { name: "Cedar", slug: "cedar" },
  { name: "Hawk", slug: "hawk" },
  { name: "Grow", slug: "grow" },
  { name: "Trainline", slug: "trainline" },
  { name: "Sanity.io", slug: "sanityio" },
  { name: "Nivoda", slug: "nivoda" },
  { name: "Aurora Solar", slug: "aurorasolar" },
  { name: "Zello", slug: "zello" },
  { name: "hyperexponential", slug: "hyperexponential" },
  { name: "The Job Sauce", slug: "thejobsauce" },
  { name: "Brigit", slug: "brigit" },
  { name: "Modern Treasury", slug: "moderntreasury" },
  { name: "Coder", slug: "coder" },
  { name: "OAK", slug: "oak" },
  { name: "Costanoa Ventures", slug: "costanoaventures" },
  { name: "RecOps On Demand", slug: "recopsondemand" },
  { name: "Lightspeed", slug: "lightspeed" },
  { name: "Reprise Financial", slug: "reprisefinancial" },
  { name: "New Story", slug: "newstory" },
  { name: "Your Remote Tech Recruiter", slug: "yourremotetechrecruiter" },
  { name: "Golden Star Labs", slug: "goldenstarlabs" },
  { name: "Hopper", slug: "hopper" },
  { name: "Luma AI", slug: "lumaai" },
  { name: "Tacto", slug: "tacto" },
  { name: "The Developer Link", slug: "thedeveloperlink" },
  { name: "Cryptio", slug: "cryptio" },
  { name: "Worldly", slug: "worldly" },
  { name: "CardFlight", slug: "cardflight" },
  { name: "Atum Works", slug: "atumworks" },
  { name: "AMPeers", slug: "ampeers" },
  { name: "Raindrop", slug: "raindrop" },
  { name: "Lifespan", slug: "lifespan" },
  { name: "Hyde", slug: "hyde" },
  { name: "Trustly", slug: "trustly" },
  { name: "MultiplyMii", slug: "multiplymii" },
  { name: "Ferocia Pty Ltd", slug: "ferociaptyltd" },
  { name: "Arthur", slug: "arthur" },
  { name: "Alpine Investors", slug: "alpineinvestors" },
  { name: "Vamo", slug: "vamo" },
  { name: "Spade", slug: "spade" },
  { name: "Ocean.", slug: "ocean" },
  { name: "HIVED", slug: "hived" },
  { name: "Hex", slug: "hex" },
  { name: "Fort", slug: "fort" },
  { name: "Arthur Robotics", slug: "arthurrobotics" },
  { name: "TransFICC", slug: "transficc" },
  { name: "SnapMagic", slug: "snapmagic" },
  { name: "Gorgias", slug: "gorgias" },
  { name: "Attentive", slug: "attentive" },
  { name: "Postscript", slug: "postscript" },
  { name: "Loop Returns", slug: "loopreturns" },
  { name: "Okendo", slug: "okendo" },
  { name: "Yotpo", slug: "yotpo" },
  { name: "Smile.io", slug: "smileio" },
  { name: "Swell", slug: "swell" },
  { name: "Privy", slug: "privy" },
];

export const BREEZY_COMPANIES: AtsCompany[] = [
  { name: "Remote Year", slug: "remote-year" },
  { name: "Vetsez", slug: "vetsez" },
  { name: "Float Health", slug: "float-health" },
  { name: "Altitude Roofing", slug: "altitude-roofing" },
  { name: "Mind Computing", slug: "mind-computing" },
  { name: "Keylime", slug: "keylime" },
  { name: "Leafr", slug: "leafr" },
  { name: "Zippee", slug: "zippee" },
  { name: "GreedyGame", slug: "greedygame" },
  { name: "Geeta Group", slug: "geeta-group" },
  { name: "Booster Box", slug: "booster-box" },
  { name: "Docebo", slug: "docebo" },
  { name: "Dodge Data and Analytics", slug: "dodge-data-and-analytics" },
  { name: "Tally", slug: "tally" },
  { name: "Portable", slug: "portable" },
  { name: "Thinkific", slug: "thinkific" },
  { name: "Brevo", slug: "brevo" },
  { name: "Sinch", slug: "sinch" },
  { name: "Vonage", slug: "vonage" },
  { name: "MessageBird", slug: "messagebird" },
  { name: "Plivo", slug: "plivo" },
  { name: "Telnyx", slug: "telnyx" },
  { name: "Bandwidth", slug: "bandwidth" },
  { name: "RingCentral", slug: "ringcentral" },
  { name: "8x8", slug: "8x8" },
  { name: "Dialpad", slug: "dialpad" },
  { name: "Talkdesk", slug: "talkdesk" },
  { name: "Five9", slug: "five9" },
  { name: "Genesys", slug: "genesys" },
  { name: "Nice InContact", slug: "nice-incontact" },
  { name: "Aircall", slug: "aircall" },
  { name: "CloudTalk", slug: "cloudtalk" },
  { name: "JustCall", slug: "justcall" },
  { name: "Krisp", slug: "krisp" },
  { name: "Otter.ai", slug: "otter-ai" },
  { name: "Descript", slug: "descript" },
  { name: "Riverside.fm", slug: "riverside-fm" },
  { name: "SquadCast", slug: "squadcast" },
  { name: "Zencastr", slug: "zencastr" },
  { name: "RedCircle", slug: "redcircle" },
  { name: "Simplecast", slug: "simplecast" },
  { name: "Transistor.fm", slug: "transistor-fm" },
  { name: "Captivate.fm", slug: "captivate-fm" },
  { name: "Buzzsprout", slug: "buzzsprout" },
  { name: "Libsyn", slug: "libsyn" },
  { name: "Blubrry", slug: "blubrry" },
  { name: "Podbean", slug: "podbean" },
  { name: "Spreaker", slug: "spreaker" },
  { name: "Audioboom", slug: "audioboom" },
  { name: "Omny Studio", slug: "omny-studio" },
  { name: "Megaphone", slug: "megaphone" },
  { name: "Triton Digital", slug: "triton-digital" },
  { name: "AdsWizz", slug: "adswizz" },
  { name: "Targetspot", slug: "targetspot" },
  { name: "DAX", slug: "dax" },
  { name: "Acast", slug: "acast" },
  { name: "Sounder.fm", slug: "sounder-fm" },
  { name: "Veritonic", slug: "veritonic" },
  { name: "Podsights", slug: "podsights" },
  { name: "Chartable", slug: "chartable" },
  { name: "Magellan AI", slug: "magellan-ai" },
  { name: "Podchaser", slug: "podchaser" },
  { name: "Listen Notes", slug: "listen-notes" },
  { name: "Podscribe", slug: "podscribe" },
  { name: "Backtracks", slug: "backtracks" },
  { name: "CoHost", slug: "cohost" },
  { name: "Quill", slug: "quill" },
  { name: "Pacific Content", slug: "pacific-content" },
  { name: "Pineapple Street", slug: "pineapple-street" },
  { name: "Gimlet", slug: "gimlet" },
  { name: "Parcast", slug: "parcast" },
  { name: "Wondery", slug: "wondery" },
  { name: "Luminary", slug: "luminary" },
  { name: "Pushkin Industries", slug: "pushkin-industries" },
  { name: "Slate", slug: "slate" },
  // Added Aug 2026 batch — 75 more Breezy HR companies
  { name: "Urrly", slug: "urrly" },
  { name: "Cefaly Technology", slug: "cefaly-technology" },
  { name: "Raising The Village", slug: "raising-the-village" },
  { name: "Viamo", slug: "viamo" },
  { name: "Stack Influence", slug: "stack-influence" },
  { name: "GraphAware", slug: "graphaware" },
  { name: "Revelo Talent Corp", slug: "revelo-talent-corp" },
  { name: "Drips", slug: "drips" },
  { name: "FocusGroupPanel", slug: "focusgrouppanel" },
  { name: "Continued", slug: "continued" },
  { name: "Third and Grove", slug: "third-and-grove" },
  { name: "Pulsara", slug: "pulsara" },
  { name: "GSD Staffing", slug: "gsd-staffing" },
  { name: "20four7VA", slug: "20four7va" },
  { name: "BetterSource", slug: "bettersource" },
  { name: "iVisa", slug: "ivisa" },
  { name: "Affordmate", slug: "affordmate" },
  { name: "Xapobank", slug: "xapobank" },
  { name: "Symetra", slug: "symetra" },
  { name: "1001", slug: "1001" },
  { name: "Trueline", slug: "trueline" },
  { name: "C3 Industries", slug: "c3-industries" },
  { name: "Plat4mation", slug: "plat4mation" },
  { name: "Developex", slug: "developex" },
  { name: "Volo", slug: "volo" },
  { name: "Scoro", slug: "scoro" },
  { name: "Teamwork", slug: "teamwork" },
  { name: "Frontify", slug: "frontify" },
  { name: "Productsup", slug: "productsup" },
  { name: "Contentstack", slug: "contentstack" },
  { name: "Storyblok", slug: "storyblok" },
  { name: "Hygraph", slug: "hygraph" },
  { name: "Prismic", slug: "prismic" },
  { name: "Octane AI", slug: "octane-ai" },
  { name: "Tydo", slug: "tydo" },
  { name: "Triple Whale", slug: "triple-whale" },
  { name: "Northbeam", slug: "northbeam" },
  { name: "Daasity", slug: "daasity" },
  { name: "Skio", slug: "skio" },
  { name: "Smartrr", slug: "smartrr" },
  { name: "Stay AI", slug: "stay-ai" },
  { name: "Retention.com", slug: "retention-com" },
  { name: "Wonderment", slug: "wonderment" },
  { name: "Malomo", slug: "malomo" },
  { name: "Gladly", slug: "gladly" },
  { name: "Ada", slug: "ada" },
  { name: "Forethought", slug: "forethought" },
  { name: "Solvvy", slug: "solvvy" },
  { name: "Netomi", slug: "netomi" },
  { name: "Fin AI", slug: "fin-ai" },
  { name: "Zowie", slug: "zowie" },
  { name: "Mavenoid", slug: "mavenoid" },
  { name: "Stonly", slug: "stonly" },
  { name: "Guidde", slug: "guidde" },
  { name: "Tango", slug: "tango" },
  { name: "Scribe", slug: "scribe" },
  { name: "Breezy HR", slug: "breezy-hr" },
  { name: "Appcues", slug: "appcues" },
  { name: "Userpilot", slug: "userpilot" },
  { name: "WalkMe", slug: "walkme" },
  { name: "Whatfix", slug: "whatfix" },
  { name: "Spekit", slug: "spekit" },
  { name: "Enable", slug: "enable" },
  { name: "Highspot", slug: "highspot" },
  { name: "Seismic", slug: "seismic" },
  { name: "Showpad", slug: "showpad" },
  { name: "Brainshark", slug: "brainshark" },
  { name: "Mindtickle", slug: "mindtickle" },
  { name: "Lessonly", slug: "lessonly" },
  { name: "Salesloft", slug: "salesloft" },
  { name: "Clari", slug: "clari" },
  { name: "BoostUp", slug: "boostup" },
  { name: "Aviso", slug: "aviso" },
  { name: "InsightSquared", slug: "insightsquared" },
  { name: "People.ai", slug: "people-ai" },
];
