// Curated company boards for public ATS feeds.
// Every slug below was verified live against its ATS API and returned at least
// one open posting at the time of generation. A board that later 404s is
// logged and skipped by the fetcher.
export interface AtsCompany {
  name: string;
  slug: string;
}

export const GREENHOUSE_COMPANIES: AtsCompany[] = [
  { name: "Affirm", slug: "affirm" },
  { name: "Aha!", slug: "aha" },
  { name: "Airtable", slug: "airtable" },
  { name: "Algolia", slug: "algolia" },
  { name: "Alpine Investors", slug: "alpineinvestors" },
  { name: "Amplitude", slug: "amplitude" },
  { name: "Arkose Labs", slug: "arkoselabs" },
  { name: "Attentive", slug: "attentive" },
  { name: "Axios", slug: "axios" },
  { name: "Bandwidth", slug: "bandwidth" },
  { name: "Betterment", slug: "betterment" },
  { name: "Bitpanda", slug: "bitpanda" },
  { name: "Blockchain.com", slug: "blockchain" },
  { name: "Branch", slug: "branch" },
  { name: "Brave", slug: "brave" },
  { name: "Braze", slug: "braze" },
  { name: "Brex", slug: "brex" },
  { name: "Carta", slug: "carta" },
  { name: "Checkr", slug: "checkr" },
  { name: "Clever", slug: "clever" },
  { name: "Cockroach Labs", slug: "cockroachlabs" },
  { name: "Coinbase", slug: "coinbase" },
  { name: "Contentstack", slug: "contentstack" },
  { name: "Coursera", slug: "coursera" },
  { name: "Customer.io", slug: "customerio" },
  { name: "Databricks", slug: "databricks" },
  { name: "Datadog", slug: "datadog" },
  { name: "Dataiku", slug: "dataiku" },
  { name: "Descope", slug: "descope" },
  { name: "Descript", slug: "descript" },
  { name: "Dialpad", slug: "dialpad" },
  { name: "Discord", slug: "discord" },
  { name: "Doximity", slug: "doximity" },
  { name: "Dremio", slug: "dremio" },
  { name: "Dropbox", slug: "dropbox" },
  { name: "Duolingo", slug: "duolingo" },
  { name: "Elastic", slug: "elastic" },
  { name: "Elation Health", slug: "elationhealth" },
  { name: "Faire", slug: "faire" },
  { name: "Fastly", slug: "fastly" },
  { name: "Figma", slug: "figma" },
  { name: "Fingerprint", slug: "fingerprint" },
  { name: "Fireblocks", slug: "fireblocks" },
  { name: "Five9", slug: "five9" },
  { name: "Fivetran", slug: "fivetran" },
  { name: "Fleetio", slug: "fleetio" },
  { name: "Flexport", slug: "flexport" },
  { name: "Forter", slug: "forter" },
  { name: "Ghost", slug: "ghost" },
  { name: "GitLab", slug: "gitlab" },
  { name: "GoCardless", slug: "gocardless" },
  { name: "Grafana Labs", slug: "grafanalabs" },
  { name: "Gremlin", slug: "gremlin" },
  { name: "Guidde", slug: "guidde" },
  { name: "Guild Education", slug: "guild" },
  { name: "Gusto", slug: "gusto" },
  { name: "HackerRank", slug: "hackerrank" },
  { name: "HealthJoy", slug: "healthjoy" },
  { name: "Hootsuite", slug: "hootsuite" },
  { name: "Imply", slug: "imply" },
  { name: "Instacart", slug: "instacart" },
  { name: "Intercom", slug: "intercom" },
  { name: "International Rescue Committee", slug: "international" },
  { name: "Iterable", slug: "iterable" },
  { name: "Jamf", slug: "jamf" },
  { name: "JetBrains", slug: "jetbrains" },
  { name: "Karat", slug: "karat" },
  { name: "Klaviyo", slug: "klaviyo" },
  { name: "Lattice", slug: "lattice" },
  { name: "LendingTree", slug: "lendingtree" },
  { name: "LinkedIn", slug: "linkedin" },
  { name: "Lucid Motors", slug: "lucidmotors" },
  { name: "Lyft", slug: "lyft" },
  { name: "Mercury", slug: "mercury" },
  { name: "Mixpanel", slug: "mixpanel" },
  { name: "MongoDB", slug: "mongodb" },
  { name: "Motive", slug: "motive" },
  { name: "Mozilla", slug: "mozilla" },
  { name: "Neo4j", slug: "neo4j" },
  { name: "Netlify", slug: "netlify" },
  { name: "New Story", slug: "new" },
  { name: "Newsela", slug: "newsela" },
  { name: "Nice InContact", slug: "nice" },
  { name: "Northbeam", slug: "northbeam" },
  { name: "Oddball", slug: "oddball" },
  { name: "Okta", slug: "okta" },
  { name: "Orca Security", slug: "orcasecurity" },
  { name: "Otter.ai", slug: "otterai" },
  { name: "Pendo", slug: "pendo" },
  { name: "PingCAP", slug: "pingcap" },
  { name: "Pinterest", slug: "pinterest" },
  { name: "PlanetScale", slug: "planetscale" },
  { name: "Portable", slug: "portable" },
  { name: "Postman", slug: "postman" },
  { name: "Postscript", slug: "postscript" },
  { name: "Qualtrics", slug: "qualtrics" },
  { name: "RedCircle", slug: "redcircle" },
  { name: "Reddit", slug: "reddit" },
  { name: "Remote", slug: "remote" },
  { name: "Robinhood", slug: "robinhood" },
  { name: "RTI International", slug: "rti" },
  { name: "Salesloft", slug: "salesloft" },
  { name: "Samsara", slug: "samsara" },
  { name: "Scout24", slug: "scout24" },
  { name: "Sendbird", slug: "sendbird" },
  { name: "Showpad", slug: "showpad" },
  { name: "SingleStore", slug: "singlestore" },
  { name: "Starburst", slug: "starburst" },
  { name: "StarTree", slug: "startree" },
  { name: "Storyblok", slug: "storyblok" },
  { name: "Stripe", slug: "stripe" },
  { name: "Triple Whale", slug: "triplewhale" },
  { name: "Twilio", slug: "twilio" },
  { name: "Upwork", slug: "upwork" },
  { name: "Vercel", slug: "vercel" },
  { name: "Vonage", slug: "vonage" },
  { name: "Webflow", slug: "webflow" },
  { name: "Wikimedia Foundation", slug: "wikimedia" },
  { name: "Winrock International", slug: "winrock" },
  { name: "Yotpo", slug: "yotpo" },
  { name: "Yugabyte", slug: "yugabyte" },
];

export const LEVER_COMPANIES: AtsCompany[] = [
  { name: "Abt Global", slug: "abt" },
  { name: "Aircall", slug: "aircall" },
  { name: "Articulate", slug: "articulate" },
  { name: "Brevo", slug: "brevo" },
  { name: "Canvas Medical", slug: "canvasmedical" },
  { name: "Cloudinary", slug: "cloudinary" },
  { name: "Enable", slug: "enable" },
  { name: "Finch", slug: "finch" },
  { name: "Getty Images", slug: "gettyimages" },
  { name: "GoPuff", slug: "gopuff" },
  { name: "Included Health", slug: "includedhealth" },
  { name: "Kinsta", slug: "kinsta" },
  { name: "Loop Returns", slug: "loopreturns" },
  { name: "Mindtickle", slug: "mindtickle" },
  { name: "Netomi", slug: "netomi" },
  { name: "Okendo", slug: "okendo" },
  { name: "Outreach", slug: "outreach" },
  { name: "Palantir", slug: "palantir" },
  { name: "People.ai", slug: "people-ai" },
  { name: "Prismic", slug: "prismic" },
  { name: "Quantum Health", slug: "quantum-health" },
  { name: "RainFocus", slug: "rainfocus" },
  { name: "Ro", slug: "ro" },
  { name: "Skio", slug: "skio" },
  { name: "Slate", slug: "slate" },
  { name: "Spotify", slug: "spotify" },
  { name: "Swissborg", slug: "swissborg" },
  { name: "Sysdig", slug: "sysdig" },
  { name: "The Athletic", slug: "theathletic" },
  { name: "Toptal", slug: "toptal" },
  { name: "WalkMe", slug: "walkme" },
  { name: "Welo Global", slug: "weloglobal" },
];

export const ASHBY_COMPANIES: AtsCompany[] = [
  { name: "1Password", slug: "1password" },
  { name: "A Place for Mom", slug: "a-place-for-mom" },
  { name: "Airbyte", slug: "airbyte" },
  { name: "AMPeers", slug: "ampeers" },
  { name: "Arthur", slug: "arthur" },
  { name: "Ashby", slug: "ashby" },
  { name: "Astronomer", slug: "astronomer" },
  { name: "Aurora Solar", slug: "aurorasolar" },
  { name: "Authzed", slug: "authzed" },
  { name: "Benchling", slug: "benchling" },
  { name: "Brigit", slug: "brigit" },
  { name: "Buffer", slug: "buffer" },
  { name: "CardFlight", slug: "cardflight" },
  { name: "Cedar", slug: "cedar" },
  { name: "Circle", slug: "circle" },
  { name: "Clerk", slug: "clerk" },
  { name: "ClickHouse", slug: "clickhouse" },
  { name: "ClickUp", slug: "clickup" },
  { name: "Close", slug: "close" },
  { name: "Coder", slug: "coder" },
  { name: "Colonist", slug: "colonist" },
  { name: "Confluent", slug: "confluent" },
  { name: "Contra", slug: "contra" },
  { name: "Cryptio", slug: "cryptio" },
  { name: "Cursor", slug: "cursor" },
  { name: "DeepL", slug: "deepl" },
  { name: "Deliveroo", slug: "deliveroo" },
  { name: "Docebo", slug: "docebo" },
  { name: "Docker", slug: "docker" },
  { name: "Envoy", slug: "envoy" },
  { name: "Etched", slug: "etched" },
  { name: "Expensify", slug: "expensify" },
  { name: "Ferocia Pty Ltd", slug: "ferocia" },
  { name: "Fin AI", slug: "fin" },
  { name: "Float", slug: "float" },
  { name: "Frontify", slug: "frontify" },
  { name: "FullStory", slug: "fullstory" },
  { name: "G2", slug: "g2" },
  { name: "G2i", slug: "g2i" },
  { name: "Gimlet", slug: "gimlet" },
  { name: "Gorgias", slug: "gorgias" },
  { name: "HackerOne", slug: "hackerone" },
  { name: "Harmonic Security", slug: "harmonic" },
  { name: "Harvey", slug: "harvey" },
  { name: "Hawk", slug: "hawk" },
  { name: "Help Scout", slug: "helpscout" },
  { name: "Hex", slug: "hex" },
  { name: "HIVED", slug: "hived" },
  { name: "Hiya", slug: "hiya" },
  { name: "Hopper", slug: "hopper" },
  { name: "Human API", slug: "human" },
  { name: "Hyde", slug: "hyde" },
  { name: "hyperexponential", slug: "hyperexponential" },
  { name: "InfluxData", slug: "influxdata" },
  { name: "Inngest", slug: "inngest" },
  { name: "Jellyfish", slug: "jellyfish" },
  { name: "Juniper Square", slug: "junipersquare" },
  { name: "Kong", slug: "kong" },
  { name: "Kustomer", slug: "kustomer" },
  { name: "Lifespan", slug: "lifespan" },
  { name: "Lightspeed", slug: "lightspeed" },
  { name: "Linear", slug: "linear" },
  { name: "Lottie", slug: "lottie" },
  { name: "Luma AI", slug: "lumaai" },
  { name: "Luminary", slug: "luminary" },
  { name: "Materialize", slug: "materialize" },
  { name: "Merge", slug: "merge" },
  { name: "Miro", slug: "miro" },
  { name: "Modern Treasury", slug: "moderntreasury" },
  { name: "MotherDuck", slug: "motherduck" },
  { name: "MultiplyMii", slug: "multiplymii" },
  { name: "Mux", slug: "mux" },
  { name: "Neon", slug: "neon" },
  { name: "Nivoda", slug: "nivoda" },
  { name: "Notion", slug: "notion" },
  { name: "Noyo", slug: "noyo" },
  { name: "OAK", slug: "oak" },
  { name: "Ocean.", slug: "ocean" },
  { name: "Paymentology", slug: "paymentology" },
  { name: "Percona", slug: "percona" },
  { name: "Persona", slug: "persona" },
  { name: "Plaid", slug: "plaid" },
  { name: "Quora", slug: "quora" },
  { name: "Railway", slug: "railway" },
  { name: "Raindrop", slug: "raindrop" },
  { name: "Ramp", slug: "ramp" },
  { name: "ReCharge Payments", slug: "recharge" },
  { name: "Redis", slug: "redis" },
  { name: "Render", slug: "render" },
  { name: "Reprise Financial", slug: "reprise" },
  { name: "Rillet", slug: "rillet" },
  { name: "Runway", slug: "runway" },
  { name: "Rutter", slug: "rutter" },
  { name: "Sanity.io", slug: "sanity" },
  { name: "Scribe", slug: "scribe" },
  { name: "Semperis", slug: "semperis" },
  { name: "Sierra", slug: "sierra" },
  { name: "SnapMagic", slug: "snapmagic" },
  { name: "Snowflake", slug: "snowflake" },
  { name: "Spade", slug: "spade" },
  { name: "Sparrow", slug: "sparrow" },
  { name: "Spekit", slug: "spekit" },
  { name: "Spruce Health", slug: "spruce" },
  { name: "Sticker Mule", slug: "stickermule" },
  { name: "Stytch", slug: "stytch" },
  { name: "Supabase", slug: "supabase" },
  { name: "Synthetic", slug: "synthetic" },
  { name: "Tacto", slug: "tacto" },
  { name: "Tailor", slug: "tailor" },
  { name: "Tango", slug: "tango" },
  { name: "Temporal", slug: "temporal" },
  { name: "Terra", slug: "terra" },
  { name: "TestGorilla", slug: "testgorilla" },
  { name: "Thinkific", slug: "thinkific" },
  { name: "Trainline", slug: "trainline" },
  { name: "TransFICC", slug: "transficc" },
  { name: "Trigger.dev", slug: "triggerdev" },
  { name: "Trustly", slug: "trustly" },
  { name: "UiPath", slug: "uipath" },
  { name: "Vanta", slug: "vanta" },
  { name: "WorkOS", slug: "workos" },
  { name: "Worldly", slug: "worldly" },
  { name: "Xero", slug: "xero" },
  { name: "Zapier", slug: "zapier" },
  { name: "Zello", slug: "zello" },
  { name: "Zencastr", slug: "zencastr" },
  { name: "Zowie", slug: "zowie" },
];

export const BREEZY_COMPANIES: AtsCompany[] = [
  { name: "1001", slug: "1001" },
  { name: "20four7VA", slug: "20four7va" },
  { name: "BetterSource", slug: "bettersource" },
  { name: "Breezy HR", slug: "breezy-hr" },
  { name: "C3 Industries", slug: "c3industries" },
  { name: "Cefaly Technology", slug: "cefaly-technology" },
  { name: "Continued", slug: "continued" },
  { name: "Developex", slug: "developex" },
  { name: "Drips", slug: "drips" },
  { name: "Float Health", slug: "float-health" },
  { name: "GraphAware", slug: "graphaware" },
  { name: "GSD Staffing", slug: "gsd-staffing" },
  { name: "Magellan AI", slug: "magellan-ai" },
  { name: "Mind Computing", slug: "mind-computing" },
  { name: "Plat4mation", slug: "plat4mation" },
  { name: "Raising The Village", slug: "raisingthevillage" },
  { name: "Revelo Talent Corp", slug: "revelo-talent-corp" },
  { name: "Trueline", slug: "trueline" },
  { name: "Urrly", slug: "urrly" },
  { name: "Vetsez", slug: "vetsez" },
];
